backend:
  name: github
  repo: VinniWe/mind-studio-website
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "uploads" # Media files will be stored in the repo under uploads
public_folder: "/uploads" # The src attribute for uploaded media

locale: "de" # Set German as default language

collections:
  # Slider Collection
  - name: "slider"
    label: "Slider"
    label_singular: "Slide"
    folder: "content/slider"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Meta Text", name: "meta", widget: "string", required: false}
      - {label: "Desktop Image", name: "image_desktop", widget: "image", required: false}
      - {label: "Mobile Image", name: "image_mobile", widget: "image", required: false}
      - {label: "CTA Text", name: "cta_text", widget: "string", default: "Mehr erfahren"}
      - {label: "CTA Link", name: "cta_link", widget: "string"}
      - {label: "Order", name: "order", widget: "number", default: 0, value_type: "int", min: 0}
      - {label: "Active", name: "active", widget: "boolean", default: true}

  # Homepage Content
  - name: "homepage"
    label: "Homepage"
    files:
      - label: "Statistics Section"
        name: "statistics"
        file: "content/homepage/statistics.md"
        fields:
          - label: "Statistics"
            name: "stats"
            widget: "list"
            fields:
              - {label: "Text", name: "text", widget: "text"}
              - {label: "Source", name: "source", widget: "string"}
      
      - label: "Services Section"
        name: "services"
        file: "content/homepage/services.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "text"}
          - label: "Individual Services"
            name: "individual"
            widget: "object"
            fields:
              - {label: "Category", name: "category", widget: "string"}
              - {label: "Heading", name: "heading", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
          - label: "Organization Services"
            name: "organizations"
            widget: "object"
            fields:
              - {label: "Category", name: "category", widget: "string"}
              - {label: "Heading", name: "heading", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
      
      - label: "Approach Section"
        name: "approach"
        file: "content/homepage/approach.md"
        fields:
          - label: "Approach Items"
            name: "items"
            widget: "list"
            fields:
              - {label: "Category", name: "category", widget: "string"}
              - {label: "Heading", name: "heading", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
      
      - label: "Testimonials"
        name: "testimonials"
        file: "content/homepage/testimonials.md"
        fields:
          - {label: "Section Title", name: "title", widget: "string"}
          - {label: "Section Subtitle", name: "subtitle", widget: "text"}
          - label: "Testimonials"
            name: "testimonials"
            widget: "list"
            fields:
              - {label: "Quote", name: "quote", widget: "text"}
              - {label: "Author Name", name: "author", widget: "string"}
              - {label: "Author Title", name: "title", widget: "string"}

  # Pages
  - name: "pages"
    label: "Seiten"
    files:
      - label: "Über Mich"
        name: "about"
        file: "content/pages/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero Image", name: "hero_image", widget: "image", required: false}
          - {label: "Biography", name: "body", widget: "markdown"}
          - label: "Qualifications"
            name: "qualifications"
            widget: "list"
            field: {label: "Qualification", name: "item", widget: "string"}
      
      - label: "Leistungen - Einzel"
        name: "services_individual"
        file: "content/pages/services-individual.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - label: "Topics"
            name: "topics"
            widget: "list"
            field: {label: "Topic", name: "item", widget: "string"}
          - label: "Process"
            name: "process"
            widget: "list"
            fields:
              - {label: "Step Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
      
      - label: "Leistungen - Organisationen"
        name: "services_organizations"
        file: "content/pages/services-organizations.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - label: "Formats"
            name: "formats"
            widget: "list"
            field: {label: "Format", name: "item", widget: "string"}
          - label: "Approach"
            name: "approach"
            widget: "list"
            fields:
              - {label: "Step Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
      
      - label: "Ansatz"
        name: "approach_page"
        file: "content/pages/approach.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "body", widget: "markdown"}
          - label: "Principles"
            name: "principles"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}

  # Settings
  - name: "settings"
    label: "Einstellungen"
    files:
      - label: "Site Settings"
        name: "site"
        file: "content/settings/site.md"
        fields:
          - {label: "Site Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Contact Email", name: "email", widget: "string"}
          - {label: "Phone", name: "phone", widget: "string"}
          - {label: "Address", name: "address", widget: "text"}
          - label: "Social Media"
            name: "social"
            widget: "object"
            fields:
              - {label: "LinkedIn", name: "linkedin", widget: "string", required: false}
              - {label: "Instagram", name: "instagram", widget: "string", required: false}
              - {label: "Facebook", name: "facebook", widget: "string", required: false}
