backend:
  name: github
  repo: VinniWe/mind-studio-website
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "uploads" # Media files will be stored in the repo under uploads
public_folder: "/uploads" # The src attribute for uploaded media

locale: "de" # Set German as default language

collections:
  # Slider Collection
  - name: "slider"
    label: "Slider"
    label_singular: "Slide"
    folder: "content/slider"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Meta Text", name: "meta", widget: "string", required: false}
      - {label: "Desktop Image", name: "image_desktop", widget: "image", required: false}
      - {label: "Mobile Image", name: "image_mobile", widget: "image", required: false}
      - {label: "CTA Text", name: "cta_text", widget: "string", default: "Mehr erfahren"}
      - {label: "CTA Link", name: "cta_link", widget: "string"}
      - {label: "Order", name: "order", widget: "number", default: 0, value_type: "int", min: 0}
      - {label: "Active", name: "active", widget: "boolean", default: true}
